accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('login/', LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    # add additional fields here...

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':_('First name')}))
    last_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':_('Last name')}))
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':_('Email address')}))
    password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':_('Password')}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':_('Confirm password')}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, get_user_model
from django.shortcuts import render, redirect
from .forms import RegistrationForm

User = get_user_model()


def registration_view(request):
    if request.user.is_authenticated:
        redirect('home')

    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        messages.success(request, 'Registration successful...')
        login(request, user)
        return redirect('home')
    return render(request, 'register.html', context={'form': form,})

templates/base.html
<!doctype html>
{% load static %}
{% spaceless %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="icon" href="{% static 'favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <title>EmailAuth - {% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">EmailAuth</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                        </li>                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    </ul>
                    {% if request.user.is_anonymous %}
                    <ul class="navbar-nav ml-auto" >
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">REGISTER</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav" >
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav><br>

        {% if messages %}
            <div class="container">
                {% for message in messages %}
                    <div class="alert alert-dismissable alert-{{ message.tags }} fade show">
                        {{ message|safe }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-sm-5">
                {% block body %}{% endblock body %}
                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>
{% endspaceless %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block body %}  
    <h2>Hi...</h2>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

 {% block body %}    
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Login</h3>
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

 {% block body %}  
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Register</h3>
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}